const String PREF_THEME = 'THEME';
const String PREF_FIRST_USE = 'FIRST_USE';
const String PREF_HIDELOCKDIALOG = 'PREF_HIDELOCKDIALOG';

const String DARK_THEME = 'DARK_THEME';
const String LIGHT_THEME = 'LIGHT_THEME';
const String NEO_THEME = 'NEO_THEME';

enum Themes { DARK_THEME, LIGHT_THEME, NEO_THEME }

const int MAX_ACCOUNTNAME_LENGTH = 40;
const int MAX_USERNAME_LENGTH = 80;
const int MAX_PASSWORD_LENGTH = 64;

const int MAX_TITLE_LENGTH = 40;
const int MAX_CONTENT_LENGTH = 2000;
